### PR TITLE
User can now log out

### LINKED ISSUE #50: User can log out
After pressing the log out button, they should be logged out from Parse and return to the Getting Started screen. The screen they were on should be dismissed

### PR DESCRIPTION
**Pull request by tahaafzal5**
Closes #50

### CODE REVIEW

**Comment by nashirj** [comment]
The logout functionality looks good to me, but you shouldn't duplicate commits; I notice you have commit `c4775c3` in this PR as well as the other one that you requested I review.

**Comment by tahaafzal5** [comment]
Ah. Are the duplicates because I branched from the sign up branch and not from the main?

**Comment by nashirj** [comment]
yeah! I think that will cause it. you can just remake the branch from main and make your changes again?

**Comment by tahaafzal5** [comment]
Yes, I’ll do that and create a PR then.

On Nov 22, 2020, at 9:23 PM, Nashir Janmohamed <notifications@github.com> wrote:

﻿

yeah! I think that will cause it. you can just remake the branch from main and make your changes again?

**Comment by tahaafzal5** [comment]
Closing this and will create a new PR.

**Pull request closed without merging**
