### PR TITLE
Text starts from the top left* instead of center.

### LINKED ISSUE #78: The description tab of the new ride offering screen should have text start in the upper left corner
Use [content insets](https://stackoverflow.com/questions/10792884/uitextview-text-not-starting-from-top)

### PR DESCRIPTION
**Pull request by tahaafzal5**
closes #78

### CODE REVIEW

**Comment by nashirj** [comment]
This is a great start! That said, the text should wrap in the text field

**Comment by tahaafzal5** [comment]
I thought it was, I’ll re-do it.

On Dec 7, 2020, at 11:27 AM, Nashir Janmohamed <notifications@github.com> wrote:

﻿

This is a great start! That said, the text should wrap in the text field

**Comment by nashirj** [comment]
Apparently, we need to use a UITextView instead. Can you make this change? https://stackoverflow.com/questions/29056830/swift-text-field-wrap-to-new-line

**Comment by tahaafzal5** [comment]
Yeah I made that change, can you review and merge in if it looks good?

**Comment by nashirj** [comment]
You need to change it to a UITextView, not a UITextField

**Comment by nashirj** [comment]
The behavior is still the same on my end

**Comment by tahaafzal5** [comment]
Ahh! I see why - fixing it now.

On Dec 7, 2020, at 12:47 PM, Nashir Janmohamed <notifications@github.com<mailto:notifications@github.com>> wrote:



The behavior is still the same on my end

**Comment by tahaafzal5** [comment]
@nashirj does it work now for you?

**Comment by nashirj** [comment]
No, does it for you?

**Comment by tahaafzal5** [comment]
That is weird - it works for me.

Screen Shot 2020-12-07 at 1 07 27 PM

**Comment by nashirj** [comment]
Sounds good. I got pretty busy with work just now, so I am not sure I can look at it until later anyway, sorry about that.

**Comment by tahaafzal5** [comment]
Yes, no worries!

**Comment by nashirj** [comment]
Are you sure that you updated the textfield to a textview on the storyboard? I see that you updated it in the viewcontroller

**Comment by tahaafzal5** [comment]
I did, but for some reason it did not commit. Can you check now?

**Comment by nashirj** [comment]
looks great now, thanks!

**Pull request merged**
