### PR TITLE
Finish implementing booking ride. 

### LINKED ISSUE #44: User can create a new ride offering
User can specify
- pickup
- destination
- cost (or alternative form of payment)
- special requests/conditions (i.e. no pets? luggage? etc)

Create button on Feed to go to this screen
When the create ride button is pressed on the create offering screen a post request is created and the ride is added to the list of rides in the server
Pressing the `create` button will add this ride to the user's list of rides

### LINKED ISSUE #45: User can accept a nearby ride offering
**Note**: the book button is found only on the Ride Details page
Pressing the `book` button will add this ride to the user's list of rides
It also opens the mail app with the email field populated so that the user can message the poster
If this ride is already in the user's list of rides or the user is the poster, should show some error

### LINKED ISSUE #75: When a user posts a ride, it should be added to their list of rides

### LINKED ISSUE #76: When a user books a ride, it should be added to their list of rides
Maybe each ride should have a list of users that have booked the ride

### LINKED ISSUE #86: Account details/populate page should populate all rides for each user (booked and posted)

### PR DESCRIPTION
**Pull request by nashirj**
Some nice to haves would be pop up messages that let users know when things go wrong, such as trying to book a ride that they posted, or booking a ride twice (which is already accounted for in the code, just need to create some popup dialog or something that lets the user know).

One thing I ran into was circular dependencies with parse (i.e. it's not possible to have a list of rides for each user and a list of users for each ride). The way I solved this was to give each ride a list of riders (which are User objects).

Close #44 close #45 close #75 close #76 close #86

### CODE REVIEW

**Comment by nashirj** [comment]
I need to make one change before this is merged, please wait on that

**Comment by nashirj** [comment]
Should be good now after you review it @tahaafzal5

**Comment by tahaafzal5** [comment]
Looks good!

I noticed that if I (logged in as Taha) go to someone else's (John D's) account details page, under the ride offerings section, I also see the rides they have booked. Is that how it should be or should I just see the rides that John D is offering. I attached a screenshot just for reference if the above isn't clear.

Screen Shot 2020-12-06 at 1 52 07 AM

**Comment by nashirj** [comment]
I see what you’re saying. I guess it makes sense to only show the rides that person is offering. I’ll change that, thanks

**Comment by tahaafzal5** [comment]
Perfect!

**Pull request merged**
