### PR TITLE
Create New Rides and Populate Ride Offering Feed

### LINKED ISSUE #43: User can see a list of all nearby ride offerings.
- Get rides from server
- Populate table view
- Format table view cells

### LINKED ISSUE #44: User can create a new ride offering
User can specify
- pickup
- destination
- cost (or alternative form of payment)
- special requests/conditions (i.e. no pets? luggage? etc)

Create button on Feed to go to this screen
When the create ride button is pressed on the create offering screen a post request is created and the ride is added to the list of rides in the server
Pressing the `create` button will add this ride to the user's list of rides

### LINKED ISSUE #48: Make table view cell populate
Profile picture should always be the poster of the ride offering
- Dates
- Destination
- Pickup
- Profile pic of poster
- First name, Last initial of poster
- Description

### PR DESCRIPTION
**Pull request by yaosarayin**
Closes #43 
Closes #44 
Closes #48

### CODE REVIEW

**Comment by tahaafzal5** [comment]
Screen Shot 2020-11-27 at 10 00 53 PM

I think the dates and times are switched. Below Sioux Falls, SD, it should be Nov 30, 10 AM and under Minneapolis, it should be Dec 18 7 AM.
Also, can you make the New Ride Offering a Scroll View? If the keyboard pops up on the Simulator, some fields are inaccessible.
And lastly, on the New Ride Offering, since we are asking for departure date & time and return trip's date & time, can you change the "Select Estimated Arrival Time" to Select Departure Time for the return trip or something like that?

**Comment by nashirj** [comment]
I'll work on this

**Comment by nashirj** [comment]
Fixed:
- swapped dates and times
- text not wrapping on the ride offerings table view
- made new ride offering screen a scroll view
- label for return trip date and time

Bugs to be fixed
- text in the details text field on the NewRideViewController should start at the top left, not middle
- date picker looks super weird on the new ride view controller screen

**Comment by nashirj** [comment]
Wait this is not ready to merge, need to fix a couple things

**Comment by nashirj** [comment]
not sure why there are conflicts above, but this is still not ready to merge, I need to finish a couple things tomorrow, sorry

**Comment by tahaafzal5** [comment]
Looks great so far though! Again, thanks so much!

**Comment by nashirj** [comment]
My pleasure! I fixed the merge conflict btw

**Comment by nashirj** [comment]
Will let you know when I finish up the rest sometime tomorrow

**Comment by tahaafzal5** [comment]
Looks good!

**Pull request merged**
