### PR TITLE
Implement Settings storyboard

### PR DESCRIPTION
**Pull request by nashirj**

### CODE REVIEW

**Comment by nashirj** [comment]
closes #8

**Comment by tahaafzal5** [comment]
I got a chance to look at it. It looks great, but can you also please add Auto Layout constraints when you get a chance? :)

**Comment by nashirj** [comment]
Thank you! I did I thought. Do they not show up on your end?

**Comment by tahaafzal5** [comment]
They don't :/

Screen Shot 2020-11-21 at 7 57 26 PM

**Comment by nashirj** [comment]
You're right, I'm seeing the same thing. I can't figure out what I'm doing wrong though. Can you help me tomorrow?

**Comment by tahaafzal5** [comment]
Yes, we can possibly look at it tomorrow (Sunday) or Monday

On Nov 22, 2020, at 12:31 AM, Nashir Janmohamed <notifications@github.com> wrote:

﻿

You're right, I'm seeing the same thing. I can't figure out what I'm doing wrong though. Can you help me tomorrow?

**Comment by nashirj** [comment]
Ok, thanks. Let me know if you have time Sunday, otherwise we can talk about it in our Monday tag up

**Comment by nashirj** [comment]
While working on navigation, I realized that there were a whole bunch of auto layout issues in the other screens as well haha. We should definitely discuss this together during our meeting

**Comment by tahaafzal5** [comment]
Definitely! I just tried a bunch of stuff with the auto layout on the arrow icon, but couldn't really understand what's happening. Maybe the easiest/quickest thing would be to remove the arrows. Thoughts?

**Comment by nashirj** [comment]
Yeah that sounds like a good approach to me! I can delete them tomorrow

**Pull request merged**
